default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blogger_development

test:
  <<: *default
  database: blogger_test

production:
  <<: *default
  database: blogger_production
  username: blogger
  password: <%= ENV['BLOGGER_DATABASE_PASSWORD'] %>
